### ISSUE TITLE
Log timestamps relative to today

### ISSUE THREAD

**Issue by MiSikora** [szymonkozak/tempomat#38]
This piggybacks on #5. I often know when something happened relative to today but I'm frustrated that I have to check the date and so on. While #5 is an interesting and cool approach it requires some effort to parse timestamp inputs. I'd like to propose a simpler solution that can be used alternatively.

We could use `t+N` to determine the date based on today. For example `tempo log ABC-123 5h t-3` would log 5 hours 3 days in the past.

**Comment by szymonkozak** [comment]
Good idea, I think that this doesn't exclude #5 and both solutions can be implemented. Your proposition sounds very simple, so if you want just open PR. :)
